// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEUxUj1vCmzXht1DnbfxKXqGquHRlIlk',
    appId: '1:491848201322:web:3938b8e177b7ae13fb4613',
    messagingSenderId: '491848201322',
    projectId: 'bookswapping-firebase',
    authDomain: 'bookswapping-firebase.firebaseapp.com',
    storageBucket: 'bookswapping-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArNSHHWHR8-ZTj9vdm3UDkfrdcFH3q6h8',
    appId: '1:491848201322:android:4f0c6e128517a732fb4613',
    messagingSenderId: '491848201322',
    projectId: 'bookswapping-firebase',
    storageBucket: 'bookswapping-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRhPUjF9ftfC4QP8Zx9M19DA02FI5YgI8',
    appId: '1:491848201322:ios:3ced945e1c98d869fb4613',
    messagingSenderId: '491848201322',
    projectId: 'bookswapping-firebase',
    storageBucket: 'bookswapping-firebase.appspot.com',
    iosBundleId: 'com.example.donationsItems',
  );
}
